### ISSUE TITLE
Doesnt work with i3-gaps

### ISSUE THREAD

**Issue by StarrKiss** [fennerm/flashfocus#28]
Flashfocus and Compton are running, nothing is happening, however. I have no idea what is happening, as the logs for both are clear and show they are both working.

**Comment by fennerm** [comment]
Could you paste the contents of your compton config file?

**Comment by thelazt16** [comment]
I have the same problem as well before. Turn out flash focus has trouble if you set opacity level to your program. For example ` "95:class_g = 'Tilix' && focused", `. So the fix is removing the opacity level and just use the `inactive-opacity = 0.80; active-opacity = .90;`.

**Comment by fennerm** [comment]
Yeah I presume flashfocus won’t work well in combination with custom config rules. Most of that functionality can be replicated using the flashfocus config file though. 

I’m going to close this due to inactivity. Flashfocus definitely works with i3 gaps so my guess is there is some inconsistent setting in your compton config. Feel free to reopen with more details.
