### ISSUE TITLE
Use nc_flash_window for flash on focus

### ISSUE THREAD

**Issue by travankor** [fennerm/flashfocus#38]
Currently, it seems that flashfocus uses the native flash when switching focus. Can a config option/flag be added to use the netcat-based flash for switching focus instead of the default?

**Comment by fennerm** [comment]
Both the netcat script and ‘flash_window’ use the same mechanism for flashing the window. Where they differ is just how they communicate with the flashfocus server. flash_window is slow only because it needs to wait for the entire python interpreter to startup before pinging the unix socket. Flashing windows on focus doesn’t have this problem because the server is constantly running and only pays for python startup once on initialization.
